//! macOS: Carbon global hotkey, pasteboard watching, simulated Cmd+V, login item.
//!
//! macOS never pushes clipboard changes, so a background thread checks the pasteboard's
//! change counter twice a second: one integer read, effectively free.

use super::{Event, send};
use objc::{class, msg_send, rc::autoreleasepool, runtime::{BOOL, Object, YES}, sel, sel_impl};
use std::{ffi::{CStr, c_void}, path::PathBuf, sync::{Mutex, atomic::{AtomicUsize, Ordering::Relaxed}, mpsc::Sender}, thread, time::Duration};

type Id = *mut Object;

/// Hotkeys offered in settings: (label, Carbon modifiers, virtual key code).
pub const HOTKEYS: [(&str, u32, u32); 5] = [
    ("option + v", OPTION, 9),
    ("cmd + shift + v", CMD | SHIFT, 9),
    ("ctrl + option + v", CONTROL | OPTION, 9),
    ("option + c", OPTION, 8),
    ("ctrl + `", CONTROL, 50),
];
const CMD: u32 = 1 << 8;
const SHIFT: u32 = 1 << 9;
const OPTION: u32 = 1 << 11;
const CONTROL: u32 = 1 << 12;

#[repr(C)]
struct EventTypeSpec { class: u32, kind: u32 }
#[repr(C)]
struct EventHotKeyId { signature: u32, id: u32 }

#[link(name = "Carbon", kind = "framework")]
unsafe extern "C" {
    fn GetApplicationEventTarget() -> *mut c_void;
    fn InstallEventHandler(
        target: *mut c_void,
        handler: extern "C" fn(*mut c_void, *mut c_void, *mut c_void) -> i32,
        count: u32,
        types: *const EventTypeSpec,
        data: *mut c_void,
        out: *mut *mut c_void,
    ) -> i32;
    fn RegisterEventHotKey(code: u32, mods: u32, id: EventHotKeyId, target: *mut c_void, options: u32, out: *mut *mut c_void) -> i32;
    fn UnregisterEventHotKey(hotkey: *mut c_void) -> i32;
}

#[link(name = "ApplicationServices", kind = "framework")]
unsafe extern "C" {
    fn AXIsProcessTrusted() -> bool;
    fn AXIsProcessTrustedWithOptions(options: Id) -> bool;
    static kAXTrustedCheckOptionPrompt: Id;
    fn CGEventCreateKeyboardEvent(source: *const c_void, key: u16, down: bool) -> *mut c_void;
    fn CGEventSetFlags(event: *mut c_void, flags: u64);
    fn CGEventPost(tap: u32, event: *mut c_void);
    fn CFRelease(obj: *const c_void);
}

/// The registered hotkey (an EventHotKeyRef), 0 if none.
static HOTKEY: Mutex<usize> = Mutex::new(0);
static HANDLER: AtomicUsize = AtomicUsize::new(0);

extern "C" fn on_hotkey(_: *mut c_void, _: *mut c_void, _: *mut c_void) -> i32 {
    send(Event::Toggle);
    0
}

/// Change the global hotkey (index into HOTKEYS). Called on the main thread.
pub fn set_hotkey(ix: usize) {
    let (_, mods, code) = HOTKEYS[ix.min(HOTKEYS.len() - 1)];
    unsafe {
        let target = GetApplicationEventTarget();
        if HANDLER.load(Relaxed) == 0 {
            // kEventClassKeyboard / kEventHotKeyPressed
            let spec = EventTypeSpec { class: u32::from_be_bytes(*b"keyb"), kind: 5 };
            let mut h = std::ptr::null_mut();
            InstallEventHandler(target, on_hotkey, 1, &spec, std::ptr::null_mut(), &mut h);
            HANDLER.store(h as usize, Relaxed);
        }
        let mut cur = HOTKEY.lock().unwrap();
        if *cur != 0 { UnregisterEventHotKey(*cur as *mut c_void); }
        let mut r = std::ptr::null_mut();
        let id = EventHotKeyId { signature: u32::from_be_bytes(*b"cobx"), id: 1 };
        RegisterEventHotKey(code, mods, id, target, 0, &mut r);
        *cur = r as usize;
    }
}

unsafe fn to_string(s: Id) -> String {
    if s.is_null() { return String::new(); }
    let p: *const std::ffi::c_char = unsafe { msg_send![s, UTF8String] };
    if p.is_null() { String::new() } else { unsafe { CStr::from_ptr(p) }.to_string_lossy().into_owned() }
}

fn pasteboard() -> Id { unsafe { msg_send![class!(NSPasteboard), generalPasteboard] } }

/// Tell `changed` every time something new is copied.
pub(super) fn watch(changed: Sender<()>) {
    thread::spawn(move || {
        let count = || -> isize { autoreleasepool(|| unsafe { msg_send![pasteboard(), changeCount] }) };
        let mut last = count();
        loop {
            thread::sleep(Duration::from_millis(500));
            let now = count();
            if now != last {
                last = now;
                if changed.send(()).is_err() { return; }
            }
        }
    });
}

/// Password managers mark their copies with these types (nspasteboard.org).
pub(super) fn is_private() -> bool {
    autoreleasepool(|| unsafe {
        let types: Id = msg_send![pasteboard(), types];
        if types.is_null() { return false; }
        let n: usize = msg_send![types, count];
        (0..n).any(|i| {
            let t: Id = msg_send![types, objectAtIndex: i];
            matches!(to_string(t).as_str(), "org.nspasteboard.ConcealedType" | "org.nspasteboard.TransientType" | "org.nspasteboard.AutoGeneratedType")
        })
    })
}

fn frontmost() -> Id {
    unsafe {
        let ws: Id = msg_send![class!(NSWorkspace), sharedWorkspace];
        msg_send![ws, frontmostApplication]
    }
}

/// Name of the app in front when the copy happened ("Safari", "Code"…).
pub(super) fn source_app() -> String {
    autoreleasepool(|| unsafe {
        let app = frontmost();
        if app.is_null() { return String::new(); }
        to_string(msg_send![app, localizedName])
    })
}

/// The frontmost app's process id. CoBox's window never activates CoBox itself, so this
/// is still the app the user was in.
pub fn foreground() -> isize {
    autoreleasepool(|| unsafe {
        let app = frontmost();
        if app.is_null() { return 0; }
        let pid: i32 = msg_send![app, processIdentifier];
        pid as isize
    })
}

/// Bring the previous app back and press Cmd+V in it. Needs Accessibility permission;
/// without it macOS is asked to show its permission prompt and the item stays copied.
pub fn paste_into(prev: isize) {
    thread::spawn(move || unsafe {
        thread::sleep(Duration::from_millis(60));
        autoreleasepool(|| {
            if prev > 0 && foreground() != prev {
                let app: Id = msg_send![class!(NSRunningApplication), runningApplicationWithProcessIdentifier: prev as i32];
                if !app.is_null() {
                    let _: BOOL = msg_send![app, activateWithOptions: 2usize]; // ignoring other apps
                    thread::sleep(Duration::from_millis(80));
                }
            }
            if !AXIsProcessTrusted() {
                let yes: Id = msg_send![class!(NSNumber), numberWithBool: YES];
                let opts: Id = msg_send![class!(NSDictionary), dictionaryWithObject: yes forKey: kAXTrustedCheckOptionPrompt];
                AXIsProcessTrustedWithOptions(opts);
                return;
            }
            for down in [true, false] {
                let e = CGEventCreateKeyboardEvent(std::ptr::null(), 9, down);
                if e.is_null() { continue; }
                CGEventSetFlags(e, 1 << 20); // command
                CGEventPost(0, e); // HID event tap
                CFRelease(e);
            }
        });
    });
}

/// Start at login on/off: a LaunchAgent pointing at this executable.
pub fn autostart(on: bool) {
    let Some(home) = std::env::var_os("HOME").map(PathBuf::from) else { return };
    let path = home.join("Library/LaunchAgents/com.erfjab.cobox.plist");
    if !on {
        std::fs::remove_file(path).ok();
        return;
    }
    let Ok(exe) = std::env::current_exe() else { return };
    let exe = exe.to_string_lossy().replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;");
    super::write_if_changed(&path, &format!(
        r#"<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.erfjab.cobox</string>
  <key>ProgramArguments</key><array><string>{exe}</string></array>
  <key>RunAtLoad</key><true/>
</dict></plist>
"#
    ));
}
